<SimpleButton>:
    orientation: 'horizontal'
    size_hint: None, None
    height: text_label.texture_size[1] + dp(10)
    width: text_label.texture_size[0] + dp(15)
    padding: [dp(8), 0, dp(8), 0]

    TextLabel:
        id: text_label
        pos_hint: {'center_y': .5, 'center_x': .5}
        text: root.label_text
        font_size: root.font_size
        font_name: 'roboto-bold'
        halign: 'center'
        valign: 'middle'
        disabled_color: 1, 1, 1, 1
        color: 1, 1, 1, 1
