languages = {
    'all': 'All',
    'eng': 'English',
    'fra': 'French',
    'gsw': 'Swiss German',
    'ita': 'Italian',
    'roh': 'Romansh',
    'hun': 'Hungarian',
    'zho': 'Chinese',
    'ara': 'Arabic',
    'ind': 'Indonesian',
    'por': 'Portuguese',
    'lao': 'Lao',
    'nld': 'Dutch',
    'pap': 'Papiamento',
    'swa': 'Swahili',
    'cat': 'Catalan',
    'run': 'Kirundi',
    'afr': 'Afrikaans',
    'nbl': 'Southern Ndebele',
    'nso': 'Northern Sotho',
    'sot': 'Southern Sotho',
    'ssw': 'Swazi',
    'tsn': 'Tswana',
    'tso': 'Tsonga',
    'ven': 'Venda',
    'xho': 'Xhosa',
    'zul': 'Zulu',
    'spa': 'Spanish',
    'cal': 'Carolinian',
    'cha': 'Chamorro',
    'mkd': 'Macedonian',
    'nfr': 'Guernésiais',
    'nor': 'Norwegian',
    'dan': 'Danish',
    'fao': 'Faroese',
    'rus': 'Russian',
    'uzb': 'Uzbek',
    'sin': 'Sinhala',
    'tam': 'Tamil',
    'ben': 'Bengali',
    'aym': 'Aymara',
    'que': 'Quechua',
    'tur': 'Turkish',
    'prs': 'Dari',
    'pus': 'Pashto',
    'tuk': 'Turkmen',
    'rar': 'Cook Islands Māori',
    'fin': 'Finnish',
    'swe': 'Swedish',
    'pov': 'Upper Guinea Creole',
    'aze': 'Azerbaijani',
    'kor': 'Korean',
    'mfe': 'Mauritian Creole',
    'ell': 'Greek',
    'hrv': 'Croatian',
    'ber': 'Berber',
    'mlg': 'Malagasy',
    'cnr': 'Montenegrin',
    'grn': 'Guaraní',
    'ukr': 'Ukrainian',
    'glv': 'Manx',
    'her': 'Herero',
    'hgm': 'Khoekhoe',
    'kwn': 'Kwangali',
    'loz': 'Lozi',
    'ndo': 'Ndonga',
    'kal': 'Greenlandic',
    'khm': 'Khmer',
    'arc': 'Aramaic',
    'ckb': 'Sorani',
    'kir': 'Kyrgyz',
    'vie': 'Vietnamese',
    'lat': 'Latin',
    'deu': 'German',
    'tvl': 'Tuvaluan',
    'hat': 'Haitian Creole',
    'bel': 'Belarusian',
    'lav': 'Latvian',
    'pau': 'Palauan',
    'fil': 'Filipino',
    'bis': 'Bislama',
    'niu': 'Niuean',
    'est': 'Estonian',
    'ron': 'Romanian',
    'tet': 'Tetum',
    'jpn': 'Japanese',
    'isl': 'Icelandic',
    'ltz': 'Luxembourgish',
    'mah': 'Marshallese',
    'nau': 'Nauru',
    'mey': 'Hassaniya',
    'tha': 'Thai',
    'sag': 'Sango',
    'tir': 'Tigrinya',
    'lit': 'Lithuanian',
    'kaz': 'Kazakh',
    'hye': 'Armenian',
    'nrf': 'Jèrriais',
    'crs': 'Seychellois Creole',
    'tgk': 'Tajik',
    'mlt': 'Maltese',
    'sqi': 'Albanian',
    'div': 'Maldivian',
    'fas': 'Persian (Farsi)',
    'bjz': 'Belizean Creole',
    'mya': 'Burmese',
    'dzo': 'Dzongkha',
    'jam': 'Jamaican Patois',
    'pol': 'Polish',
    'zdj': 'Comorian',
    'bwg': 'Chibarwe',
    'kck': 'Kalanga',
    'khi': 'Khoisan',
    'ndc': 'Ndau',
    'nde': 'Northern Ndebele',
    'nya': 'Chewa',
    'sna': 'Shona',
    'toi': 'Tonga',
    'zib': 'Zimbabwean Sign Language',
    'mon': 'Mongolian',
    'heb': 'Hebrew',
    'mri': 'Māori',
    'nzs': 'New Zealand Sign Language'
}
subregions = ['Antarctic', 'Caribbean', 'Western Europe', 'Western Africa', 'Central Europe', 'Eastern Asia', 'Polynesia', 'Northern Africa', 'Southern Europe', 'South-Eastern Asia', 'Eastern Africa', 'Southern Africa', 'North America', 'Middle Africa', 'Micronesia', 'Southeast Europe', 'Western Asia', 'Northern Europe', 'Melanesia', 'Central Asia', 'Southern Asia', 'South America', 'Australia and New Zealand', 'Central America', 'Eastern Europe']
regions = ['Antarctic', 'Americas', 'Africa', 'Europe', 'Asia', 'Oceania']