<FilterContainer>:
    orientation: 'horizontal'
    size_hint: 1, None
    height: dp(60)
    spacing: 10

    # example of filter widget:
#    AutoSuggestionInputBox:
#        id: filter_regions
#        label_text: 'Region'
#        size_hint_x: None
#        width: dp(150)
#        options: root.regions
#        selected_option: 'All'
#        default_option: 'All'
#        enhanced: True
#        filter_widget_index: 0